### PR TITLE
1. Add support for compiling in esp idf and added esp32 assembly optimizations

### PR DESCRIPTION
**Pull request by kel30a**
I noticed in the README.md, you had stated that you had intentionally "removed all optimized processor specific code (e.g. for ARM, 386 and mips), so that it will compile with the same code on all environements."

I'm hoping you mean you removed them because they weren't useful to the arduino port?

I have created the optimized processor specific code for the esp32 as it was unable to decode HE-AACv2 (Aka AAC with SBR & PS) fast enough to output to my i2s source (Note: I also had to increase the i2s_chan_config_t.dma_frame_num = 4096 for it to play smoothly. I will create another PR for this shortly)

Let me know if you need anything more or think I've done anything wrong.

### CODE REVIEW

**Comment by pschatzmann** [comment]
Correct: the assembler files from different processors were giving comile errors in Arduino.
#if defined(ESP32) is applying to all ESP processor families (including S2, S3, C2, C3, C6...)
Are you sure that your assember works for all of them ?

**Comment by kel30a** [comment]
I think it will only work for the xtensa series, I will make another PR tonight.

**Comment by pschatzmann** [comment]
I extended the ESP32 3.0 I2S API a bit to use the buffer_size and buffer_count to calculate the dma_frame_num.
This way the API is consistent with the ESP32 2.0 I2S API

**Comment by pschatzmann** [comment]
I added a [test case for the decoder to the audio tools](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/tests/codecs/test-codec-aac-fdk-dec/test-codec-aac-fdk-dec.ino)

**Comment by kel30a** [comment]
> I extended the ESP32 3.0 I2S API a bit to use the buffer_size and buffer_count to calculate the dma_frame_num. This way the API is consistent with the ESP32 2.0 I2S API

I'm not sure I understand your naming reference of "ESP32 3.0 I2S", I can see you've made that change in src\AudioI2S\I2SESP32V1.h

**Comment by pschatzmann** [comment]
ESPI2SV1.h is using for the I2S API >= IDF 5.0 which available since the Arduino ESP 3.0.
ESPI2S.h is for the old API

**Comment by kel30a** [comment]
> ESPI2SV1.h is using for the I2S API >= IDF 5.0 which available since the Arduino ESP 3.0. ESPI2S.h is for the old API, which had proper support for buffer_size and buffer_count...

Thanks - I understand now.

**Pull request merged**
